# Generated by Django 3.0.4 on 2020-03-13 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('cellular', models.TextField(blank=True, max_length=40, null=True)),
                ('name', models.TextField(blank=True, max_length=50)),
                ('surname', models.TextField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unspecified')], default='U', max_length=1)),
                ('country', models.CharField(choices=[('IT', 'Italy'), ('US', 'United States'), ('FR', 'France')], default='IT', max_length=2)),
                ('language', models.CharField(choices=[('IT', 'Italy'), ('EN', 'English')], default='EN', max_length=2)),
                ('ui_pref', models.CharField(choices=[('L', 'Light'), ('D', 'Dark'), ('A', 'Auto')], default='A', max_length=1)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
