# Generated by Django 3.0.7 on 2020-06-14 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('user', '0002_auto_20200611_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country', models.CharField(choices=[('IT', 'Italy'), ('US', 'United States'), ('FR', 'France')], default='IT', max_length=2)),
                ('language', models.CharField(choices=[('IT', 'Italy'), ('EN', 'English')], default='EN', max_length=2)),
                ('ui_pref', models.CharField(choices=[('L', 'Light'), ('D', 'Dark'), ('A', 'Auto')], default='A', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ui_pref',
        ),
    ]
