# Generated by Django 3.0.7 on 2020-06-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200614_0842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
