# Generated by Django 3.0.7 on 2020-06-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResetPasswordToken',
        ),
    ]
